server:
  port: 7860
  address: 0.0.0.0
lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.1"
      snapshot: false
  server:
    password: "youshallnotpass"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: true
      http: true
      local: false
    filters:
      volume: true
      equalizer: true
      channelMix: true
      distortion: true
      lowPass: true
      rotation: true
      timescale: true
      tremolo: true
      vibrato: true

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - WEB_REMIX
      - ANDROID_MUSIC
      - WEB
      - WEB_EMBEDDED_PLAYER
      - ANDROID_VR
      - TV
    oauth:
      enabled: true
      refreshToken: "1//05EXyBGuy5j7uCgYIARAAGAUSNwF-L9IrV6U4m3efeVlA9zEyZJFiNnnRD27c9X7BDQhknfQPP_7TzCn7TdbJTnp9gfqiBa4bmK4"
    remoteCipher:
      url: "https://cipher.kikkia.dev"
